### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by itsOdell** [TheNightmareX/pennfoster-helper#1]
is this still working? how do I setup and add as a chrome extension? which tools are needed to download and run the script?
please help me from starting point

**Comment by Char2sGu** [comment]
it's still working, but it indeed takes a few steps to set it up though. tutorials will be added soon

**Comment by Char2sGu** [comment]
well I uploaded the build result as a zip file in the latest release instead, you can install it just like how you install other extensions in developer mode

**Comment by itsOdell** [comment]
ok thanks :D

**Comment by itsOdell** [comment]
hey man you seem really cool and enthusiastic, id like to connect with you on some other platforms (linkedin, discord, etc..) and collaborate together on some projects if your okay with that 😃

**Comment by Char2sGu** [comment]
thanks! I'll be glad to help ^_^ you may reach me at discord via Char2s#1688. it's late night here so i may not respond until tomorrow though

**Comment by Char2sGu** [comment]
close as solved. reopen it at anytime if you have other questions :)
